In [109]:
library(tidyverse)
library(lubridate)
air_quality <- read_csv("AirQualityUCI.csv") |>
#    select(-"...16", -"...17") |>
#    filter("CO(GT)" != -200.0, "PT08.S1(CO)" != -200, "NMHC(GT)" != -200, "PT08.S2(NMHC)" != -200, "NOx(GT)" != -200, "PT08.S3(NOx)" != -200, "NO2(GT)" != -200, "PT08.S4(NO2)" != -200, "PT08.S5(O3)" != -200, na.rm = TRUE) |>
    slice(1:9357) |>
    mutate(Year = year(mdy(Date))) |>
    mutate(Month = month(mdy(Date))) |>
    mutate(Day = day(mdy(Date))) |>
    select(Time, PT08.S1_CO, T, RH, AH, Year, Month, Day) |>
    filter(PT08.S1_CO != -200)
air_quality

New names:
• `` -> `...16`
• `` -> `...17`
Rows: 9471 Columns: 17
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (1): Date
dbl  (13): CO_GT, PT08.S1_CO, NMHC_GT, C6H6_GT, PT08.S2_NMHC, Nox_GT, PT08.S...
lgl   (2): ...16, ...17
time  (1): Time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

     Time     PT08.S1_CO T    RH   AH     Year Month Day
1    18:00:00 1360       13.6 48.9 0.7578 2004 3     10
2    19:00:00 1292       13.3 47.7 0.7255 2004 3     10
3    20:00:00 1402       11.9 54.0 0.7502 2004 3     10
4    21:00:00 1376       11.0 60.0 0.7867 2004 3     10
5    22:00:00 1272       11.2 59.6 0.7888 2004 3     10
6    23:00:00 1197       11.2 59.2 0.7848 2004 3     10
7    00:00:00 1185       11.3 56.8 0.7603 2004 3     11
8    01:00:00 1136       10.7 60.0 0.7702 2004 3     11
9    02:00:00 1094       10.7 59.7 0.7648 2004 3     11
10   03:00:00 1010       10.3 60.2 0.7517 2004 3     11
11   04:00:00 1011       10.1 60.5 0.7465 2004 3     11
12   05:00:00 1066       11.0 56.2 0.7366 2004 3     11
13   06:00:00 1052       10.5 58.1 0.7353 2004 3     11
14   07:00:00 1144       10.2 59.6 0.7417 2004 3     11
15   08:00:00 1333       10.8 57.4 0.7408 2004 3     11
16   09:00:00 1351       10.5 60.6 0.7691 2004 3     11
17   10:00:00 1233       10.8 58.4 0.7552 2004 3     11
18   11:00:00 1179       10.5 57.9 0.7352 2004 3     11
19   12:00:00 1236        9.5 66.8 0.7951 2004 3     11
20   13:00:00 1286        8.3 76.4 0.8393 2004 3     11
21   14:00:00 1371        8.0 81.1 0.8736 2004 3     11
22   15:00:00 1310        8.3 79.8 0.8778 2004 3     11
23   16:00:00 1292        9.7 71.2 0.8569 2004 3     11
24   17:00:00 1383        9.8 67.6 0.8185 2004 3     11
25   18:00:00 1581       10.3 64.2 0.8065 2004 3     11
26   19:00:00 1776        9.7 69.3 0.8319 2004 3     11
27   20:00:00 1640        9.6 67.8 0.8133 2004 3     11
28   21:00:00 1313        9.1 64.0 0.7419 2004 3     11
29   22:00:00  965        8.2 63.4 0.6905 2004 3     11
30   23:00:00  913        8.2 60.8 0.6657 2004 3     11
⋮    ⋮        ⋮          ⋮    ⋮    ⋮      ⋮    ⋮     ⋮
8962 09:00:00 1022       17.8 30.7 0.6205 2005 4     3
8963 10:00:00  970       21.1 23.7 0.5875 2005 4     3
8964 11:00:00 1000       24.0 19.3 0.5673 2005 4     3
8965 12:00:00  996       26.5 16.4 0.5594 2005 4     3
8966 13:00:00  928       28.7 13.7 0.5302 2005 4     3
8967 14:00:00  933       28.5 13.1 0.5002 2005 4     3
8968 15:00:00  956       30.0 11.1 0.4624 2005 4     3
8969 16:00:00  968       29.4 10.4 0.4192 2005 4     3
8970 17:00:00  953       28.9  9.9 0.3866 2005 4     3
8971 18:00:00 1015       22.8 21.7 0.5945 2005 4     3
8972 19:00:00 1248       19.9 33.0 0.7608 2005 4     3
8973 20:00:00 1180       17.5 40.7 0.8073 2005 4     3
8974 21:00:00 1102       16.4 46.6 0.8642 2005 4     3
8975 22:00:00 1116       15.5 49.0 0.8579 2005 4     3
8976 23:00:00 1100       14.3 52.5 0.8497 2005 4     3
8977 00:00:00 1012       14.2 51.4 0.8275 2005 4     4
8978 01:00:00  944       13.8 51.2 0.8058 2005 4     4
8979 02:00:00  912       12.1 56.3 0.7927 2005 4     4
8980 03:00:00  887       11.3 58.9 0.7888 2005 4     4
8981 04:00:00  864       11.8 56.0 0.7743 2005 4     4
8982 05:00:00  888       10.4 59.9 0.7550 2005 4     4
8983 06:00:00 1031        9.5 63.1 0.7531 2005 4     4
8984 07:00:00 1384        9.7 61.9 0.7446 2005 4     4
8985 08:00:00 1446       13.5 48.9 0.7553 2005 4     4
8986 09:00:00 1297       18.2 36.3 0.7487 2005 4     4
8987 10:00:00 1314       21.9 29.3 0.7568 2005 4     4
8988 11:00:00 1163       24.3 23.7 0.7119 2005 4     4
8989 12:00:00 1142       26.9 18.3 0.6406 2005 4     4
8990 13:00:00 1003       28.3 13.5 0.5139 2005 4     4
8991 14:00:00 1071       28.5 13.1 0.5028 2005 4     4

In [ ]:
air_quality_summarized <- air_quality |>
    group_by(Month, Year) |>
    summarize(monthly_mean = mean(PT08.S1_CO))
air_quality_summarized

air_quality_mean <- merge(air_quality, air_quality_summarized, by = c("Year", "Month"))
air_quality_mean

`summarise()` has grouped output by 'Month', 'Year', 'T', 'RH'. You can
override using the `.groups` argument.

     Month Year T    RH   AH     monthly_mean
1    1     2005 1.0  54.7 0.3657  766
2    1     2005 1.4  52.3 0.3591  774
3    1     2005 1.4  53.1 0.3642  847
4    1     2005 1.4  53.8 0.3687  776
5    1     2005 1.6  51.0 0.3561  801
6    1     2005 1.6  52.9 0.3692  790
7    1     2005 1.7  54.1 0.3785  874
8    1     2005 1.8  63.3 0.4464 1257
9    1     2005 1.9  49.7 0.3528  793
10   1     2005 2.1  73.1 0.5289  954
11   1     2005 2.4  60.2 0.4426 1222
12   1     2005 2.4  71.9 0.5288  911
13   1     2005 2.4  86.6 0.6369  978
14   1     2005 2.5  51.0 0.3778  879
15   1     2005 2.5  54.1 0.4017  879
16   1     2005 2.6  58.6 0.4385  795
17   1     2005 2.6  63.2 0.4721  915
18   1     2005 2.7  43.2 0.3259  805
19   1     2005 2.7  53.3 0.4006  859
20   1     2005 2.7  53.9 0.4062  744
21   1     2005 2.8  43.8 0.3308  790
22   1     2005 2.8  49.0 0.3700  925
23   1     2005 2.8  49.1 0.3726  867
24   1     2005 2.8  54.4 0.4110  774
25   1     2005 2.9  42.8 0.3276  971
26   1     2005 2.9  48.7 0.3706  888
27   1     2005 2.9  49.0 0.3725  865
28   1     2005 2.9  49.7 0.3782  900
29   1     2005 3.0  43.4 0.3337  801
30   1     2005 3.0  49.1 0.3774  861
⋮    ⋮     ⋮    ⋮    ⋮    ⋮      ⋮
8959 12    2004 17.3 57.1 1.1161 1173
8960 12    2004 17.4 23.3 0.4599 1135
8961 12    2004 17.4 53.3 1.0528 1357
8962 12    2004 17.5 30.8 0.6095 1250
8963 12    2004 17.6 19.9 0.3952  929
8964 12    2004 17.7 51.5 1.0315 1181
8965 12    2004 17.7 68.3 1.3713 1648
8966 12    2004 17.8 21.0 0.4234  974
8967 12    2004 17.8 23.6 0.4766 1095
8968 12    2004 17.9 66.3 1.3499 1332
8969 12    2004 18.0 58.0 1.1901 1338
8970 12    2004 18.1 20.8 0.4274  934
8971 12    2004 18.1 21.3 0.4396  920
8972 12    2004 18.1 62.1 1.2822 1456
8973 12    2004 18.3 19.5 0.4044  986
8974 12    2004 18.4 19.7 0.4117  926
8975 12    2004 18.4 52.6 1.1064 1171
8976 12    2004 18.5 52.9 1.1174 1221
8977 12    2004 18.7 53.0 1.1322 1189
8978 12    2004 18.8 20.0 0.4278  941
8979 12    2004 18.8 49.3 1.0581 1289
8980 12    2004 18.8 62.7 1.3506 1332
8981 12    2004 18.9 18.9 0.4091  991
8982 12    2004 19.0 61.6 1.3407 1493
8983 12    2004 19.2 47.1 1.0371 1199
8984 12    2004 19.2 57.9 1.2757 1405
8985 12    2004 19.4 47.1 1.0510 1257
8986 12    2004 19.4 49.8 1.1095 1316
8987 12    2004 19.5 50.1 1.1225 1208
8988 12    2004 20.3 47.5 1.1187 1145

In [ ]:
air_quality_plot <- ggplot(air_quality, aes(x = Month, y = PT08.S1_CO)) +
    geom_point()
air_quality_plot